[build]

publish = "."

functions = "netlify/netlify/functions"



[functions]

directory = "netlify/netlify/functions"

node_bundler = "esbuild"

external_node_modules = ["stripe", "@supabase/supabase-js"]
